version: '3.8'

services:
  app:
    image: local/reflex-app
    environment:
      DB_URL: sqlite:///data/reflex.db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - db-data:/app/data
       - upload-data:/app/uploaded_files
    ports:
      - "8000:8000"
      - "3000:3000"
    restart: always

  webserver:
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    ports:
      - 443:443
      - 80:80
    build:
      context: .
      dockerfile: Caddy.Dockerfile
    volumes:
       - caddy-data:/root/.caddy
    restart: always
    depends_on:
      - app

volumes:
  db-data:
  upload-data:
  caddy-data:
