version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis
    depends_on:
      - redis

  webserver:
    image: caddy:2.1.1-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./app/.web/_static:/usr/share/caddy
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
